### PR TITLE
71 improve migration rules in ABM

### LINKED ISSUE #71: Improve migration rules in ABM
Currently, persons (agents) in the ABM follow a very simple routine. The python model has more advanced rules. Please analyze what rules are missing and implement them. Some rules may be implemented differently (or even wrong), those need to be discussed and maybe changed. Properties of persons or locations can be added if needed.

### LINKED ISSUE #111: Add the variable going to school/work time
The agents should go to school/work on random times, in this issue the feature should be added to make the time of going to school/work dependent on the person. Therefore a random variable should be added to each person and the time of going to work should be calculated based on that. Consider that this feature should be adopted to the different time steps in case the time step is not 1 hour but smaller or bigger.

### PR DESCRIPTION
**Pull request by majabedi**
## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [x] New code adheres with the [coding guidelines](coding-guidelines)
* [x] Tests for new functionality has been added
* [x] A local test was succesful
* [x] There is appropriate **documentation** of your work. (use doxygen style comments)
* [x] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [x] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [x] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [ ] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [ ] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [ ] There are appropriate **unit tests** and they pass.
* [ ] The git history is clean and linearized for the merge request.
* [ ] Coverage report for new code is acceptable. 

Closes #111

### CODE REVIEW

File: cpp/models/abm/person.cpp [hunk 1]
```diff
@@ -137,6 +140,20 @@ bool Person::goes_to_work(TimePoint t, const AbmMigrationParameters& params) con
     return m_random_workgroup < params.get<WorkRatio>().get_matrix_at(t.days())[0];
 }
 
+int Person::get_go_to_work_hour(const AbmMigrationParameters& params) const
+{
+    int Minimum_Goto_Work_time = params.get<GotoWorkTimeMinimum>()[m_age];
+    int Maximum_Goto_Work_time = params.get<GotoWorkTimeMaximum>()[m_age];
+    return Minimum_Goto_Work_time+(int) ((Maximum_Goto_Work_time-Minimum_Goto_Work_time+1)*m_random_goto_work_hour);
```
Comment (dabele) [inline cpp/models/abm/person.cpp:147]: If I understand this correctly, you are adding `1` to `max - min` so the result after integer truncating can be `max`. I think there is a better way to do this. Also, the time step of the simulation may not be fixed anyway, so rounding to whole hours may cause problems.

I would suggest doing the calculation using `TimeSpan`, which has a better resolution than hours and is semantically clearer. so `t_work = tmin + (tmax - tmin) * r`. Then either go to work if `t + 0.5 * dt >= t_work` or if `t >= t_work`, not sure which is better, just a question of which rounding to use. probably `t + 0.5 * dt >= t_work` is better, since the expected value will be `(max + min) * 0.5`.

File: cpp/models/abm/person.cpp [hunk 2]
```diff
@@ -137,6 +140,20 @@ bool Person::goes_to_work(TimePoint t, const AbmMigrationParameters& params) con
     return m_random_workgroup < params.get<WorkRatio>().get_matrix_at(t.days())[0];
 }
 
+int Person::get_go_to_work_hour(const AbmMigrationParameters& params) const
+{
+    int Minimum_Goto_Work_time = params.get<GotoWorkTimeMinimum>()[m_age];
```
Comment (dabele) [inline cpp/models/abm/person.cpp:145]: we use all lower case variable names.

File: cpp/models/abm/parameters.h [hunk 3]
```diff
@@ -224,10 +224,43 @@ struct SocialEventRate {
     }
 };
 
+struct GotoWorkTimeMinimum {
+    using Type = CustomIndexArray<int, AbmAgeGroup>;
```
Comment (dabele) [inline cpp/models/abm/parameters.h:228]: I think this could be `TimeSpan` instead of `int`. Semantically more consistent.

**Review by dabele — CHANGES_REQUESTED** [review]

**Comment by majabedi** [comment]
Closes #111 totally and only one part of #71

File: cpp/models/abm/parameters.h (hunk 3 above)
Comment (majabedi) [reply cpp/models/abm/parameters.h]: This is done.

File: cpp/models/abm/person.cpp (hunk 2 above)
Comment (majabedi) [reply cpp/models/abm/person.cpp]: done

File: cpp/models/abm/person.cpp [hunk 4]
```diff
@@ -137,6 +140,24 @@ bool Person::goes_to_work(TimePoint t, const AbmMigrationParameters& params) con
     return m_random_workgroup < params.get<WorkRatio>().get_matrix_at(t.days())[0];
 }
 
+TimeSpan Person::get_go_to_work_time(const AbmMigrationParameters& params, TimeSpan dt) const
+{
+    TimeSpan minimum_goto_work_time = params.get<GotoWorkTimeMinimum>()[m_age];
+    TimeSpan maximum_goto_work_time = params.get<GotoWorkTimeMaximum>()[m_age];
+    int timeSlots = (maximum_goto_work_time.seconds() - minimum_goto_work_time.seconds()) / dt.seconds();
+    int seconds_after_minimum = int (timeSlots * m_random_goto_work_hour) * dt.seconds();
+    return minimum_goto_work_time+ mio::seconds(seconds_after_minimum);
```
Comment (dabele) [inline cpp/models/abm/person.cpp:149]: I don't quite understand why you need to use dt here. doesn't it cancel out?

**Review by dabele — CHANGES_REQUESTED** [review]

File: cpp/models/abm/migration_rules.cpp [hunk 5]
```diff
@@ -46,11 +46,13 @@ LocationType random_migration(const Person& person, TimePoint t, TimeSpan dt, co
...
 
-LocationType go_to_school(const Person& person, TimePoint t, TimeSpan /*dt*/, const AbmMigrationParameters& params)
+LocationType go_to_school(const Person& person, TimePoint t, TimeSpan dt, const AbmMigrationParameters& params)
 {
     auto current_loc = person.get_location_id().type;
+    int seconds_of_day = 60*60*24;
+
     if (current_loc == LocationType::Home && t < params.get<LockdownDate>() && t.day_of_week() < 5 &&
-        t.hour_of_day() >= 8 && person.get_age() == AbmAgeGroup::Age5to14 && person.goes_to_school(t, params) &&
+        (t.seconds() - person.get_go_to_school_time(params, dt).seconds())%(seconds_of_day) == 0 && person.get_age() == AbmAgeGroup::Age5to14 && person.goes_to_school(t, params) &&
```
[the remark this answers is not in the document]
Comment (majabedi) [reply cpp/models/abm/migration_rules.cpp:55]: I agree.
@dabele  Does this method(time_since_midnight) exist or I create it?

[the remark this answers is not in the document]
Comment (dabele) [reply cpp/models/abm/migration_rules.cpp:55]: does not exist yet but should be easy to implement, similar to the `hour_of_the_day()` method but not rounding to hours and returning a TimeSpan instead of int.

[the remark this answers is not in the document]
Comment (majabedi) [reply cpp/models/abm/migration_rules.cpp]: Ok. This is done.

File: cpp/models/abm/migration_rules.cpp [hunk 6]
```diff
@@ -61,13 +63,14 @@ LocationType go_to_school(const Person& person, TimePoint t, TimeSpan /*dt*/, co
...
-LocationType go_to_work(const Person& person, TimePoint t, TimeSpan /*dt*/, const AbmMigrationParameters& params)
+LocationType go_to_work(const Person& person, TimePoint t, TimeSpan dt, const AbmMigrationParameters& params)
 {
     auto current_loc = person.get_location_id().type;
+    int seconds_of_day = 60*60*24;
 
     if (current_loc == LocationType::Home && t < params.get<LockdownDate>() &&
         (person.get_age() == AbmAgeGroup::Age15to34 || person.get_age() == AbmAgeGroup::Age35to59) &&
-        t.day_of_week() < 5 && t.hour_of_day() >= 8 && person.goes_to_work(t, params) && !person.is_in_quarantine()) {
+        t.day_of_week() < 5 && (t.seconds() - person.get_go_to_work_time(params, dt).seconds())%(seconds_of_day) == 0 && person.goes_to_work(t, params) && !person.is_in_quarantine()) {
```
[the remark this answers is not in the document]
Comment (majabedi) [reply cpp/models/abm/migration_rules.cpp]: Done

File: cpp/models/abm/person.cpp (hunk 4 above)
Comment (majabedi) [reply cpp/models/abm/person.cpp]: with the new changes that I did above I also could change this method. So it does not have the dt anymore!

**Review by dabele — APPROVED** [review]
