### PR TITLE
326 add extensive testing scheme to abm modell

### LINKED ISSUE #326: Add extensive Testing Scheme to ABM-modell
Currently, there are rudimentary possibilities to test a person in the ABM, see #6. We want to extend this.

Especially we need:

— Different stages of testing
— Capacity of tests
— Focus on specific subgroups, e.g., kids, older, symptomatic, event goers

Finally, we need to discuss which scheme makes sense.

### LINKED ISSUE #368: Not allowed to go home when testing at home
**Describe the bug**
When testing with TestingSchemes at home and the test is positive, people are no longer allowed to enter their homes. Homes should be the fallback case of where to go when quarantined, so we somehow have to allow going there despite positive tests. Not allowing tests at home is not a solution, since it is commonly done and also done to get out of quarantine ("freitesten").

**To Reproduce**
In branch #326 
Unit test `TEST(TestTestingScheme, runScheme)` shows this (don't confuse with the fact that the test passes).

**Expected behavior**
People should be able to go home even if tested positive.

### PR DESCRIPTION
**Pull request by DavidKerkmann**
## Merge Request - GuideLine Checklist 

**Guideline** to check code before resolve WIP and approval, respectively.
As many checkboxes as possible should be ticked.

### Checks by code author:
* [x] There is at least one issue associated with the pull request.
* [x] The branch follows the naming conventions as defined in the [git workflow](git-workflow).
* [x] New code adheres with the [coding guidelines](coding-guidelines)
* [x] Tests for new functionality has been added
* [x] A local test was succesful
* [x] There is appropriate **documentation** of your work. (use doxygen style comments)
* [ ] If new third party software is used, did you pay attention to its license? Please remember to add it to the wiki after successful merging.
* [ ] If new mathematical methods or epidemiological terms are used, has the glossary been updated ? Did you provide further documentation ?
 is present or referenced. Please provide your references.
* [ ] The following questions are addressed in the documentation*:  Developers (what did you do?, how can it be maintained?), For users (how to use your work?), For admins (how to install and configure your work?)
* For documentation: Please write or update the Readme in the current working directory!

### Checks by code reviewer(s):
* [x] Is the code clean of development artifacts e.g., unnecessary comments, prints, ...
* [x] The ticket goals for each associated issue are reached or problems are clearly addressed (i.e., a new issue was introduced).
* [x] There are appropriate **unit tests** and they pass.
* [x] The git history is clean and linearized for the merge request.
* [x] Coverage report for new code is acceptable. 

closes #326, closes #368

### CODE REVIEW

**Comment by DavidKerkmann** [comment]
Since we both implemented certain parts of the test, we need to decide on one implementation and remove the other one.

**Comment by mknaranja** [comment]
@DavidKerkmann @xsaschako Could you please ensure that the code coverage runs? I think there are still untested lines and it would be good to have the coverage. It needs test-py-epidata. Maybe you need to merge the current main for that?

File: cpp/models/abm/world.cpp [hunk 1]
```diff
@@ -100,6 +100,9 @@ void World::migration(TimePoint t, TimeSpan dt)
             std::make_pair(&go_to_icu, std::vector<LocationType>{LocationType::Hospital, LocationType::ICU}),
             std::make_pair(&go_to_quarantine, std::vector<LocationType>{LocationType::Home})};
     }
+
+    update_testing_scheme_activity_status(t);
```
Comment (mknaranja) [inline cpp/models/abm/world.cpp:104]: Why is this here? Isn't this something that needs to be in world::evolve? this has nothing to do with migration

File: cpp/models/abm/world.cpp [hunk 2]
```diff
@@ -100,6 +100,9 @@ void World::migration(TimePoint t, TimeSpan dt)
             std::make_pair(&go_to_icu, std::vector<LocationType>{LocationType::Hospital, LocationType::ICU}),
             std::make_pair(&go_to_quarantine, std::vector<LocationType>{LocationType::Home})};
```
Comment (mknaranja) [inline cpp/models/abm/world.cpp:101]: I cannot comment on the previous lines since you did not change them but I asked myself why do we set the migration rules new for every day?

File: cpp/models/abm/world.cpp [hunk 3]
```diff
@@ -111,11 +114,11 @@ void World::migration(TimePoint t, TimeSpan dt)
             if (nonempty) {
                 auto target_type = rule.first(*person, t, dt, m_migration_parameters);
                 Location* target = find_location(target_type, *person);
-                if (target != &get_location(*person)) {
-                    if (target->get_testing_scheme().run_scheme(*person, m_testing_parameters)) {
+                if (run_testing_schemes(*person, *target)) {
```
Comment (mknaranja) [inline cpp/models/abm/world.cpp:117]: singular!

File: cpp/models/abm/world.h [hunk 4]
```diff
@@ -186,12 +185,32 @@ class World
...
+     */
+    bool run_testing_schemes(Person& person, const Location& location);
+
 private:
     void interaction(TimePoint t, TimeSpan dt);
     void migration(TimePoint t, TimeSpan dt);
 
     std::vector<std::unique_ptr<Person>> m_persons;
     std::vector<std::vector<Location>> m_locations;
+    std::vector<TestingScheme> m_testing_schemes;
```
Comment (mknaranja) [inline cpp/models/abm/world.h:213]: see my comment above. We should only have one scheme at a time..

File: cpp/models/abm/world.h [hunk 5]
```diff
@@ -186,12 +185,32 @@ class World
...
+     * @param t time point to be updated for
+     */
+    void update_testing_scheme_activity_status(const TimePoint t);
+    
+    /**
+     * runs all testing schemes for a given person and a given location
+     * @param person person to be checked
+     * @param location location to be checked
+     */
+    bool run_testing_schemes(Person& person, const Location& location);
```
Comment (mknaranja) [inline cpp/models/abm/world.h:205]: singular, see above

File: cpp/tests/test_abm.cpp [hunk 6]
```diff
@@ -1481,3 +1420,148 @@ TEST(TestDiscreteDistribution, generate)
...
+    testing_rule.add_infection_state(mio::abm::InfectionState::Infected);
+    testing_rule.add_infection_state(mio::abm::InfectionState::Carrier);
+    testing_rule.add_location_type(mio::abm::LocationType::Home);
+    testing_rule.add_location_type(mio::abm::LocationType::Work);
+
+    const auto testing_frequency = mio::abm::days(1);
+    const auto start_date        = mio::abm::TimePoint(20);
+    const auto end_date          = mio::abm::TimePoint(60 * 60 * 24 * 3);
+    const auto probability       = 1.0;
+    const auto test_type         = mio::abm::PCRTest();
```
Comment (mknaranja) [inline cpp/tests/test_abm.cpp:1551]: please test for all kinds of tests

File: cpp/tests/test_abm.cpp [hunk 7]
```diff
@@ -1481,3 +1420,148 @@ TEST(TestDiscreteDistribution, generate)
...
+
+    auto testing_scheme =
+        mio::abm::TestingScheme({testing_rule}, testing_frequency, start_date, end_date, probability, test_type);
+
+    world.add_testing_scheme(testing_scheme);
+    auto current_time = mio::abm::TimePoint(0);
+    ASSERT_EQ(world.run_testing_schemes(person, work), true);
```
Comment (mknaranja) [inline cpp/tests/test_abm.cpp:1558]: Why is this true? doesnt it start at Time 20?

File: cpp/tests/test_abm.cpp [hunk 8]
```diff
@@ -1481,3 +1420,148 @@ TEST(TestDiscreteDistribution, generate)
...
+{
+    auto world   = mio::abm::World();
+    auto home_id = world.add_location(mio::abm::LocationType::Home);
+    auto work_id = world.add_location(mio::abm::LocationType::Work);
+    auto person  = mio::abm::Person(home_id, mio::abm::InfectionState::Infected, mio::abm::AgeGroup::Age15to34,
+                                    world.get_global_infection_parameters());
+    auto& home   = world.get_individualized_location(home_id);
+    auto& work   = world.get_individualized_location(work_id);
+    person.set_assigned_location(home);
+    person.set_assigned_location(work);
```
Comment (mknaranja) [inline cpp/tests/test_abm.cpp:1434]: we should avoid using unnecessary objects in tests. world is not needed here. directly create the location.

File: cpp/tests/test_abm.cpp [hunk 9]
```diff
@@ -1481,3 +1420,148 @@ TEST(TestDiscreteDistribution, generate)
...
+    auto current_time = mio::abm::TimePoint(0);
+    ASSERT_EQ(world.run_testing_schemes(person, work), true);
+    current_time = mio::abm::TimePoint(30);
+    world.update_testing_scheme_activity_status(current_time);
+    ScopedMockDistribution<testing::StrictMock<MockDistribution<mio::UniformDistribution<double>>>> mock_uniform_dist;
+    EXPECT_CALL(mock_uniform_dist.get_mock(), invoke)
+        .Times(testing::AtLeast(2))
+        .WillOnce(testing::Return(0.7))
+        .WillOnce(testing::Return(0.4));
+    ASSERT_EQ(world.run_testing_schemes(person, work), false);
```
Comment (mknaranja) [inline cpp/tests/test_abm.cpp:1566]: I do not understand this. If it returns 0.7 or 0.4, this is below the probability of 1.0 and the test should be executed, right?

Furthermore, there are many execution branches untested, e.g., if return larger probability, if test frequency says no test needed etc.

File: cpp/tests/test_abm.cpp [hunk 10]
```diff
@@ -1481,3 +1420,148 @@ TEST(TestDiscreteDistribution, generate)
...
+    auto testing_scheme =
+        mio::abm::TestingScheme(testing_rules, testing_frequency, start_date, end_date, probability, test_type);
+
+    std::vector<mio::abm::InfectionState> test_infection_states2 = {mio::abm::InfectionState::Recovered_Carrier};
+    std::vector<mio::abm::LocationType> test_location_types2     = {mio::abm::LocationType::Home};
+    auto testing_rule2 = mio::abm::TestingRule({}, test_location_types2, test_infection_states2);
+    testing_scheme.add_testing_rule(testing_rule2);
+
+    auto loc_home = mio::abm::Location(mio::abm::LocationType::Home, 0);
+    auto loc_work = mio::abm::Location(mio::abm::LocationType::Home, 0);
```
Comment (mknaranja) [inline cpp/tests/test_abm.cpp:1504]:
```suggestion
    auto loc_work = mio::abm::Location(mio::abm::LocationType::Work, 0);
```
????

**error**

File: cpp/tests/test_abm.cpp [hunk 11]
```diff
@@ -1481,3 +1420,148 @@ TEST(TestDiscreteDistribution, generate)
...
+
+    ScopedMockDistribution<testing::StrictMock<MockDistribution<mio::UniformDistribution<double>>>> mock_uniform_dist;
+    EXPECT_CALL(mock_uniform_dist.get_mock(), invoke)
+        .Times(testing::AtLeast(4))
+        .WillOnce(testing::Return(0.7))
+        .WillOnce(testing::Return(0.5))
+        .WillOnce(testing::Return(0.7))
+        .WillOnce(testing::Return(0.5));
+    ASSERT_EQ(testing_scheme.run_scheme(person1, loc_home), false);
+    ASSERT_EQ(testing_scheme.run_scheme(person2, loc_work), true);
```
Comment (mknaranja) [inline cpp/tests/test_abm.cpp:1517]: There is an **error** above

**Review by mknaranja — COMMENTED** [review]
I really like the new implementation, thanks a lot @DavidKerkmann and @xsaschako. There is only one major issue: To my understanding there is always only one TestingScheme at a time (see certain comments). Currently there is no error handling for overlapping schemes etc

Maybe a better solution for std::vector testing_schemes could be given by our dampings implementation, i.e, a vector of pairs which a formed by a scheme and a start day. The scheme that has the highest start_day < t (with t the current time) is then always active.

Certain minor issues also given in the comments.

File: cpp/models/abm/parameters.h [hunk 12]
```diff
@@ -233,7 +233,19 @@ struct TestParameters {
     double specificity;
 };
 
-struct AntigenTest {
+struct GenericTest {
+    using Type = TestParameters;
+    static constexpr Type get_default()
+    {
+        return Type{0.9, 0.99};
+    }
```
[the remark this answers is not in the document]
Comment (DavidKerkmann) [reply cpp/models/abm/parameters.h:241]: We first tried to make the generic test pure virtual (which would be logical since there is no generic tests to practical use). However, when using the line
return !person.get_tested(m_test_type.get_default());
in the run of the test, the compiler wasn't aware of any get_default() function of a generic test. I thought it would know that it can only be instanced by classes that inherit the generic test and therefore have to have this function, since it is required by the pure virtual generic test class. But since that didn't work, we did this. Maybe then the template is the good solution. We should discuss this briefly.

File: cpp/models/abm/person.cpp [hunk 13]
```diff
@@ -84,12 +83,6 @@ void Person::interact(TimeSpan dt, const GlobalInfectionParameters& global_infec
         new_infection_state == InfectionState::Infected_Critical) {
         m_quarantine = true;
     }
-    else if (new_infection_state == InfectionState::Infected) {
-        double rand = UniformDistribution<double>::get_instance()();
-        if (rand < global_infection_params.get<TestWhileInfected>()[this->m_age] * dt.days()) {
```
[the remark this answers is not in the document]
Comment (DavidKerkmann) [reply cpp/models/abm/person.cpp:89]: It is not. If we want to have tests for infected persons, this has now to be done by a `TestingScheme` with a rule that tests any person with infection state `Infected` with a given probability. This removes the hard-coded auto-test for infected people. If this functionality is always intended, one could add this scheme in the initialisation of the world.

Or did your comment refer to removing `TestWhileInfected`? :D

File: cpp/models/abm/world.h [hunk 14]
```diff
@@ -186,12 +185,32 @@ class World
     void use_migration_rules(bool param);
     bool use_migration_rules() const;
 
+    /**
+     * adds a testing scheme to the set of all testing schemes for the simulation
+     * @param testing_scheme testing scheme to be added
+     */
+    void add_testing_scheme(const TestingScheme& testing_scheme);
```
[the remark this answers is not in the document]
Comment (DavidKerkmann) [reply cpp/models/abm/world.h:192]: This implementation allows for multiple testing schemes to (co-)exist. Indeed, one testing scheme is built from multiple testing rules to express different things to be tested. For example, you might want to test all people going to school and also all people above 60 (independent of location) for some reason. This would be covered by two rules within the same testing scheme. Another testing scheme however could test all infected people (independent of the age and location) with a certain probability. This is currently not possible to implement in one scheme without putting the probability in the testing rule. We should discuss this.

File: cpp/examples/abm.cpp [hunk 15]
```diff
@@ -276,14 +278,32 @@ void create_assign_locations(mio::abm::World& world)
...
+        mio::abm::LocationType::School, mio::abm::LocationType::Work, mio::abm::LocationType::BasicsShop};
+
+    auto testing_rule1                               = mio::abm::TestingRule({}, test_location_types, {});
+    std::vector<mio::abm::TestingRule> testing_rules = {testing_rule1};
+
+    const auto testing_frequency = mio::abm::days(2);
+    const auto start_date        = mio::abm::TimePoint(0);
+    const auto end_date          = mio::abm::TimePoint(0) + mio::abm::days(60);
+    const auto probability       = 0.8;
+    const auto test_type         = mio::abm::PCRTest();
```
[the remark this answers is not in the document]
Comment (xsaschako) [reply cpp/examples/abm.cpp:301]: I think this is resolved after our discussion.

**Review by xsaschako — COMMENTED** [review]
Major issue with one object managing the testing schemes got added.
There are some tests missing

File: cpp/models/abm/world.h (hunk 14 above)
[the remark this answers is not in the document]
Comment (xsaschako) [reply cpp/models/abm/world.h]: solved by adding a testingstrategy

File: cpp/models/abm/world.cpp (hunk 3 above)
Comment (xsaschako) [reply cpp/models/abm/world.cpp]: Resolved through the implementation of testingStrategy.

File: cpp/models/abm/testing_strategy.h [hunk 16]
```diff
@@ -0,0 +1,249 @@
...
+public:
+    /**
+     * Create a testing strategy.
+     * @param testing_schemes vector of testing schemes that are checked for testing
+     */
+    TestingStrategy() = default;
+    explicit TestingStrategy(const std::vector<TestingScheme>& testing_schemes);
+    /**
+     * Compares two testing strategies for equality.
+     * Compare references. Still possible to clone strategies.
```
Comment (mknaranja) [inline cpp/models/abm/testing_strategy.h:215]: remove?

**Review by mknaranja — CHANGES_REQUESTED** [review]
In https://github.com/DLR-SC/memilio/blob/326-add-extensive-testing-scheme-to-abm-modell/cpp/models/abm/location.h#L189 we have 

`LocalInfectionParameters m_parameters;`

Do we need this as well as their getters anymore?

Missing unit test review.

File: cpp/models/abm/person.cpp [hunk 17]
```diff
@@ -178,6 +178,7 @@ bool Person::get_tested(const TestParameters& params)
             return false;
         }
         else {
+            m_quarantine = true;
```
[the remark this answers is not in the document]
Comment (DavidKerkmann) [reply cpp/models/abm/person.cpp:181]: I don't know why it shows as after the return for you. In the version of the file that is pushed here, the return statement is last. Nevertheless, I have added comments for the individual sections to make it more clear. Comment: We also changed the unit test of get_tested to account for this case.

File: cpp/models/abm/testing_strategy.cpp [hunk 18]
```diff
@@ -103,29 +103,29 @@ bool TestingRule::has_requested_infection_state(const Person& p) const
...
-    , m_testing_frequency(testing_frequency)
+TestingScheme::TestingScheme(const std::vector<TestingCriteria>& testing_criteria,
+                             TimeSpan minimal_time_since_last_test, TimePoint start_date, TimePoint end_date,
+                             double probability, const GenericTest& test_type)
+    : m_testing_criteria(testing_criteria)
+    , m_minimal_time_since_last_test(minimal_time_since_last_test)
     , m_probability(probability)
     , m_start_date(start_date)
     , m_end_date(end_date)
     , m_test_type(test_type)
```
[the remark this answers is not in the document]
Comment (DavidKerkmann) [reply cpp/models/abm/testing_strategy.cpp:114]: I changed the order at every place to an order which I think fits well.

File: cpp/models/abm/testing_strategy.cpp [hunk 19]
```diff
@@ -139,18 +139,54 @@ void TestingScheme::update_activity_status(const TimePoint t)
...
+{
+    return std::all_of(m_testing_schemes.begin(), m_testing_schemes.end(), [&person, location](TestingScheme ts) {
+        if (ts.is_active()) {
+            return ts.run_scheme(person, location);
+        }
+        return true;
+    });
+}
+
+void TestingStrategy::update_testing_scheme_activity_status(const TimePoint t)
```
[the remark this answers is not in the document]
Comment (DavidKerkmann) [reply cpp/models/abm/testing_strategy.cpp:184]: We can do that. Remember that this is the same name as the function `TestingScheme::update_activity_status`. I have changed it for now.

File: pycode/memilio-epidata/memilio/epidata_test/test_epidata_geoModificationGermany.py [hunk 20]
```diff
@@ -390,6 +390,7 @@ def test_get_official_county_table(self):
             if(name not in county_table.columns.tolist()):
                 self.assertFalse("headers have changed.")
 
+    @unittest.skip("Link doesn't work for CI. Needs to be fixed.")
```
[the remark this answers is not in the document]
Comment (DavidKerkmann) [reply pycode/memilio-epidata/memilio/epidata_test/test_epidata_geoModificationGermany.py:393]: Fixed.

File: cpp/tests/test_abm.cpp [hunk 21]
```diff
@@ -1421,111 +1445,98 @@ TEST(TestDiscreteDistribution, generate)
...
-    ASSERT_EQ(testing_scheme.run_scheme(person2, loc_work), true);
-
-    ASSERT_EQ(person1.is_in_quarantine(), true);
-    ASSERT_EQ(person2.is_in_quarantine(), false);
-    ASSERT_EQ(person2.get_time_since_negative_test(), mio::abm::days(0));
+        .WillOnce(testing::Return(0.5))
+        .WillOnce(testing::Return(0.9));
+    ASSERT_EQ(testing_scheme.run_scheme(person1, loc_home), false); // Person tests and tests positive
+    ASSERT_EQ(testing_scheme.run_scheme(person2, loc_work), true); // Person tests and  tests negative
+    ASSERT_EQ(testing_scheme.run_scheme(person1, loc_home), true); // Person doesn't test
```
Comment (mknaranja) [inline cpp/tests/test_abm.cpp:1532]: I don't understand. Why does the person not test here? Because it tested positive shortly before? Then if return of run_scheme is if the person is allowed to enter or not, it should return the same as before, shouldnt it?

**Review by mknaranja — COMMENTED** [review]
only one comment/question

File: cpp/models/abm/testing_strategy.h (hunk 16 above)
Comment (DavidKerkmann) [reply cpp/models/abm/testing_strategy.h:215]: I removed the whole comparison operator, since I don't think we need it. I also adjusted some of the other comments of the other comparison operators.

File: cpp/tests/test_abm.cpp (hunk 21 above)
Comment (DavidKerkmann) [reply cpp/tests/test_abm.cpp:1532]: Since the person just got tested and the minimal time of repeated testing is >0, it will not get tested again. Therefore, by the scheme, the person is now allowed to enter, since no test is performed.

Obviously, the person is in quarantine after the first test. Therefore, in a real scenario, a new location cannot be chosen by the MigrationRules. Checking for quarantine is NOT the task of the TestingScheme (at this point). This can be discussed.

Comment: To be allowed to enter a (new) location, ALL testing schemes have to allow the person to go there. If you would call run_strategy twice, and there is no testing scheme with minimal time = 0, then it could actually change the result from the first call. This has to be avoided. Right now, this is fine since run_strategy is only ever called once for each location (where quarantine has already be checked for in the MigrationRules).

File: cpp/examples/abm.cpp [hunk 22]
```diff
@@ -278,7 +278,6 @@ void create_assign_locations(mio::abm::World& world)
     // People have to get tested in the 2 days before the event
```
[the remark this answers is not in the document]
Comment (DavidKerkmann) [reply cpp/examples/abm.cpp:278]: I changed the example to fit the descriptions in the comments.
The local infection parameters describe the maximum amount of contacts and are used. Thus, I will not delete them. One could consider a rename.

**Comment by mknaranja** [comment]
@DavidKerkmann Whats the status? :)

**Comment by DavidKerkmann** [comment]
Closes #368 with the last change to `run_strategy`.

**Comment by DavidKerkmann** [comment]
> @DavidKerkmann What s the status? :)

Should be good to go. Only a download test fails, which we didn't touch.

File: pycode/memilio-simulation/memilio/simulation/abm.cpp [hunk 23]
```diff
@@ -150,24 +149,31 @@ PYBIND11_MODULE(_simulation_abm, m)
...
+    py::class_<mio::abm::PCRTest, mio::abm::GenericTest>(m, "PCRTest")
+        .def(py::init<>());
+    
     py::class_<mio::abm::TestingScheme>(m, "TestingScheme")
-        .def(py::init<mio::abm::TimeSpan, double>(), py::arg("interval"), py::arg("probability"))
-        .def_property("interval", &mio::abm::TestingScheme::get_interval, &mio::abm::TestingScheme::set_interval)
-        .def_property("probability", &mio::abm::TestingScheme::get_probability,
-                      &mio::abm::TestingScheme::set_probability);
-
+        .def(py::init<const std::vector<mio::abm::TestingCriteria>&, mio::abm::TimeSpan, mio::abm::TimePoint, mio::abm::TimePoint, mio::abm::GenericTest, double>(), py::arg("testing_criteria"), py::arg("testing_min_time_since_last_test"), py::arg("start_date"), py::arg("end_date"), py::arg("test_type"), py::arg("probability"))
```
Comment (mknaranja) [inline pycode/memilio-simulation/memilio/simulation/abm.cpp:163]:
```suggestion
        .def(py::init<const std::vector<mio::abm::TestingCriteria>&, mio::abm::TimeSpan, mio::abm::TimePoint, mio::abm::TimePoint, const mio::abm::GenericTest&, double>(), py::arg("testing_criteria"), py::arg("testing_min_time_since_last_test"), py::arg("start_date"), py::arg("end_date"), py::arg("test_type"), py::arg("probability"))
```

I haven't worked with pybind for a while but why not const& on GenericTest here?

**Review by mknaranja — COMMENTED** [review]
Two minor changes required or to be denied with a reason, then we can finally merge it :)

File: pycode/memilio-simulation/memilio/simulation/abm.cpp (hunk 23 above)
Comment (DavidKerkmann) [reply pycode/memilio-simulation/memilio/simulation/abm.cpp:163]: Simply forgot it, fixed it.

**Review by mknaranja — APPROVED** [review]
