### PR TITLE
815 mock distributions for test consistencyStochasticMobility

### LINKED ISSUE #815: Add Mocks for the random values in test consistencyStochasticMobility
### Bug description

test fails and is not really nice because it depends on the random values.

### Version

Linux

### To reproduce

Test TestGraphSimulation, consistencyStochasticMobility fails. The random values should be mocked, otherwise the test design can be improved

### Relevant log output

_No response_

### Add any relevant information, e.g. used compiler, screenshots.

_No response_

### Checklist

- [ ] Attached labels, especially loc:: or model:: labels.
- [ ] Linked to project

### PR DESCRIPTION
**Pull request by reneSchm**
# Changes and Information

Please **briefly list the changes** made, additional Information and what the Reviewer should look out for:

- Replace generators for DiscreteDistribution and ExponentialDistribution by pregenerated results, s.t. the test no longer depends on RNG

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/DLR-SC/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/DLR-SC/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes and code coverage is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)

Closes #815

### CODE REVIEW

File: cpp/tests/test_graph_simulation.cpp [hunk 1]
```diff
@@ -201,18 +202,39 @@ TEST(TestGraphSimulation, consistencyStochasticMobility)
...
+        .WillOnce(testing::Return(0.446415))
+        .WillOnce(testing::Return(1.04048))
+        .WillOnce(testing::Return(0.136687))
+        .WillOnce(testing::Return(2.50697))
+        .WillOnce(testing::Return(1.61943))
+        .WillOnce(testing::Return(0.267578))
+        .WillOnce(testing::Return(1.03696))
+        .WillOnce(testing::Return(0.58395))
+        .WillOnce(testing::Return(0.113943))
+        .WillOnce(testing::Return(1.204045));
```
Comment (dabele) [inline cpp/tests/test_graph_simulation.cpp:220]: maybe a comment what effect each value has/should have (one comment for each value if necessary, one comment at the top otherwise)

**Review by dabele — CHANGES_REQUESTED** [review]

File: cpp/tests/test_graph_simulation.cpp (hunk 1 above)
Comment (reneSchm) [reply cpp/tests/test_graph_simulation.cpp:222]: I added one comment for all values, since they are all assigned to the same variable, at two places in advance.

**Review by dabele — APPROVED** [review]
